const double cornerRadius = 8;

const String patientBox = 'patientBox';
const String caseBox = 'caseBox';

const List<String> frontBodyPartsName = [
  'forehead',
  'right_ear',
  'left_ear',
  'chin',
  'sternum',
  'right_shoulder',
  'left_shoulder',
  'right_forearm',
  'left_forearm',
  'right_hand',
  'left_hand',
  'right_stomach',
  'left_stomach',
  'navel',
  'right_thigh',
  'left_thigh',
  'right_patella',
  'left_patella',
  'right_foot',
  'left_foot',
  'right_toe',
  'left_toe',
  'between_feet',
];

const List<String> backBodyPartsName = [
  'head',
  'right_ear',
  'left_ear',
  'neck',
  'right_neck',
  'left_neck',
  'right_shoulder',
  'left_shoulder',
  'right_forearm.ong',
  'left_forearm.ong',
  'right_waist',
  'left_waist',
  'right_hand',
  'left_hand',
  'right_hip',
  'left_hip',
  'hip',
  'tail',
  'right_leg',
  'left_leg',
  'right_ankle',
  'left_ankle',
  'right_foot',
  'left_foot',
  'right_sole',
  'left_sole',
];

const List<String> rightBodyPartsName = [
  'ear',
  'neck',
  'piggyback',
  'shoulder',
  'chest',
  'tail',
  'hip',
  'stomach',
  'leg',
  'ankle',
  'toe',
];
